apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: cite
  name: cite
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cite
  template:
    metadata:
      labels:
        k8s-app: cite
    spec:
      containers:
      - name: cite
        image: kakaocorp/cite:latest
        env:
        - name: CONFIG_PATH
          value: /etc/cite/build.conf
        volumeMounts:
        - name: config-volume
          mountPath: /etc/cite
        ports:
        - name: http
          containerPort: 8010
        - name: pb
          containerPort: 9989
      volumes:
        - name: config-volume
          configMap:
            name: cite-config
